using System.Collections.Generic;
using System.Linq;
using SimWorld.Defs;
using SimWorld.Sim;
using SimWorld.Tests.Content;
using Xunit;

// See ResearchTests.cs for why every production type is aliased explicitly here.
using ResearchManager = global::SimWorld.Research.ResearchManager;
using ResearchProjectDef = global::SimWorld.Research.ResearchProjectDef;
using EndlessResearch = global::SimWorld.Research.EndlessResearch;
using EraDef = global::SimWorld.Research.EraDef;

namespace SimWorld.Tests.Research
{
    /// <summary>
    /// Validates the large authored tech tree generated by tools/content/gen_techtree.py: scale (>=200
    /// projects, >=18 per era), DAG shape (same-or-earlier-era prerequisites, no bare roots outside the
    /// first era), authoring quality (unique labels, non-empty descriptions, a known track tag), the cost
    /// bands from the design brief, and a prerequisite chain deep enough to read as real historical
    /// progression rather than a shallow shopping list.
    /// </summary>
    public class TechTreeTests : ContentTestBase
    {
        private readonly ResearchManager manager;

        // Mirrors the era cost bands and track vocabulary from tools/content/gen_techtree.py, so this
        // test is an independent check on the generated content rather than a re-statement of the script.
        private static readonly Dictionary<string, (float Min, float Max)> EraCostBands = new Dictionary<string, (float Min, float Max)>
        {
            ["SticksAndStones"] = (100f, 300f),
            ["Agrarian"] = (250f, 600f),
            ["Bronze"] = (500f, 1000f),
            ["Classical"] = (800f, 1500f),
            ["Medieval"] = (1200f, 2200f),
            ["Industrial"] = (2000f, 3600f),
            ["Information"] = (3200f, 5200f),
            ["Exotic"] = (4800f, 9000f),
        };

        private static readonly HashSet<string> KnownTracks = new HashSet<string>
        {
            "SurvivalFood", "MaterialsCrafts", "ConstructionSettlement", "AgricultureAnimals",
            "SocietyGovernance", "KnowledgeWriting", "BeliefCulture", "Warfare", "TradeEconomy",
            "MedicineHealth", "EnergyIndustry", "TransportExploration", "InformationComputation", "FrontierExotic",
        };

        private const int MinTotalProjects = 200;
        private const int MinProjectsPerEra = 18;
        private const int MinChainDepth = 20;

        public TechTreeTests(CoreContentFixture content) : base(content)
        {
            manager = new ResearchManager();
            Find.ResearchManager = manager;
        }

        /// <summary>
        /// The authored tree. Endless tech (<c>research.endless</c>) mints real <see cref="ResearchProjectDef"/>s
        /// into the same database at run time, and they deliberately break the invariants this file asserts —
        /// they carry no era, and the first of each track is a root outside the first era — because they come
        /// after the ladder rather than inside it. These tests are about the content, so they read the
        /// content.
        /// </summary>
        private static IReadOnlyList<ResearchProjectDef> AllProjects =>
            DefDatabase<ResearchProjectDef>.AllDefsListForReading
                .Where(p => !EndlessResearch.IsGenerated(p))
                .ToList();

        /// <summary>The project's track tag: whichever of its tags is in <see cref="KnownTracks"/>, or null.</summary>
        private static string? TrackOf(ResearchProjectDef project)
        {
            if (project.tags == null) return null;
            foreach (string tag in project.tags)
            {
                if (KnownTracks.Contains(tag)) return tag;
            }
            return null;
        }

        [Fact]
        public void At_least_200_projects_are_loaded()
        {
            Assert.True(AllProjects.Count >= MinTotalProjects,
                $"expected at least {MinTotalProjects} research projects, found {AllProjects.Count}.");
        }

        [Fact]
        public void Every_era_has_at_least_18_projects()
        {
            foreach (EraDef era in DefDatabase<EraDef>.AllDefsListForReading)
            {
                Assert.True(era.Projects.Count >= MinProjectsPerEra,
                    $"{era.defName} has {era.Projects.Count} projects, expected at least {MinProjectsPerEra}.");
            }
        }

        [Fact]
        public void Three_middle_eras_have_at_least_25_projects()
        {
            foreach (string eraName in new[] { "Bronze", "Classical", "Medieval" })
            {
                EraDef era = DefDatabase<EraDef>.GetNamed(eraName);
                Assert.True(era.Projects.Count >= 25, $"{eraName} has {era.Projects.Count} projects, expected at least 25.");
            }
        }

        [Fact]
        public void Every_non_root_project_has_at_least_one_prerequisite_and_roots_are_confined_to_the_first_era()
        {
            EraDef firstEra = DefDatabase<EraDef>.AllDefsListForReading.OrderBy(e => e.order).First();

            foreach (ResearchProjectDef project in AllProjects)
            {
                bool hasVisible = project.prerequisites != null && project.prerequisites.Count > 0;
                bool hasHidden = project.hiddenPrerequisites != null && project.hiddenPrerequisites.Count > 0;
                bool isRoot = !hasVisible && !hasHidden;

                if (isRoot)
                {
                    Assert.True(project.era == firstEra,
                        $"{project.defName} is a root project outside the first era ({project.era?.defName}).");
                }
            }
        }

        [Fact]
        public void Every_prerequisite_is_from_the_same_or_an_earlier_era()
        {
            foreach (ResearchProjectDef project in AllProjects)
            {
                Assert.NotNull(project.era);
                int order = project.era!.order;
                if (project.prerequisites == null) continue;
                foreach (ResearchProjectDef prereq in project.prerequisites)
                {
                    Assert.NotNull(prereq.era);
                    Assert.True(prereq.era!.order <= order,
                        $"{project.defName}'s prerequisite {prereq.defName} is from a later era.");
                }
            }
        }

        [Fact]
        public void Every_costs_falls_inside_its_eras_cost_band()
        {
            foreach (ResearchProjectDef project in AllProjects)
            {
                string eraName = project.era!.defName;
                Assert.True(EraCostBands.TryGetValue(eraName, out (float Min, float Max) band), $"no known cost band for era {eraName}.");
                Assert.True(project.baseCost >= band.Min && project.baseCost <= band.Max,
                    $"{project.defName} costs {project.baseCost}, outside the {eraName} band [{band.Min}, {band.Max}].");
            }
        }

        [Fact]
        public void Every_project_has_a_description_and_a_known_track_tag()
        {
            foreach (ResearchProjectDef project in AllProjects)
            {
                Assert.False(string.IsNullOrWhiteSpace(project.description), $"{project.defName} has no description.");
                string? track = TrackOf(project);
                Assert.True(track != null, $"{project.defName} has no track tag from the known list.");
            }
        }

        [Fact]
        public void No_two_projects_share_a_label()
        {
            var byLabel = AllProjects.GroupBy(p => p.label).Where(g => g.Count() > 1).ToList();
            Assert.True(byLabel.Count == 0,
                "duplicate labels: " + string.Join("; ", byLabel.Select(g => g.Key + " -> " + string.Join(", ", g.Select(p => p.defName)))));
        }

        [Fact]
        public void The_longest_prerequisite_chain_is_at_least_20_deep()
        {
            var depth = new Dictionary<ResearchProjectDef, int>();

            int DepthOf(ResearchProjectDef project)
            {
                if (depth.TryGetValue(project, out int cached)) return cached;
                if (project.prerequisites == null || project.prerequisites.Count == 0)
                {
                    depth[project] = 1;
                    return 1;
                }
                int d = 1 + project.prerequisites.Max(DepthOf);
                depth[project] = d;
                return d;
            }

            int maxDepth = AllProjects.Max(DepthOf);
            Assert.True(maxDepth >= MinChainDepth, $"longest prerequisite chain is {maxDepth} deep, expected at least {MinChainDepth}.");
        }

        [Fact]
        public void DebugSetAllProjectsFinished_completes_every_era()
        {
            manager.DebugSetAllProjectsFinished();

            foreach (EraDef era in DefDatabase<EraDef>.AllDefsListForReading)
            {
                Assert.True(era.IsComplete, era.defName + " is not complete.");
            }
            Assert.Null(manager.NextEra);
        }

        [Fact]
        public void Exotic_era_projects_are_tagged_Frontier()
        {
            EraDef exotic = DefDatabase<EraDef>.GetNamed("Exotic");
            Assert.True(exotic.Projects.Count > 0);
            foreach (ResearchProjectDef project in exotic.Projects)
            {
                Assert.True(project.tags != null && project.tags.Contains("Frontier"),
                    $"{project.defName} (Exotic) is not tagged Frontier.");
            }
        }
    }
}
