using System;
using System.Collections.Generic;
using System.Globalization;

using SimWorld.Letters;
using SimWorld.Pawns;
using SimWorld.Pawns.Generation;
using SimWorld.Sim;
using SimWorld.World;

namespace SimWorld.Director
{
    /// <summary>
    /// A wanderer asks to join, and afterwards a real citizen is standing there (RimWorld:
    /// <c>IncidentWorker_WandererJoin</c>).
    ///
    /// <para/><b>What this replaces.</b> A stub in <c>IncidentWorker.cs</c> whose entire body was
    /// <c>=&gt; true</c>, under a doc comment that called it a "placeholder until pawn generation exists".
    /// Pawn generation had existed for a long time. The consequence is the same shape
    /// <see cref="IncidentWorker_ManhunterPack"/> and <see cref="IncidentWorker_Disease"/> each record for
    /// their own predecessors, and it is the shape this project cares most about: shipped content pointing at
    /// a worker that reports success and does nothing. <c>WandererJoin</c> is selected by the storyteller,
    /// spends its twelve-day refire timer and is written to the chronicle — while the population does not
    /// move. Every instrument downstream, the probe's <c>pop</c> column included, was being told a person had
    /// arrived who did not exist.
    ///
    /// <para/><b>Why it matters more than one incident's worth.</b> <c>docs/design/the-loop.md</c> makes
    /// pressure scale with the player's own growth, and pressure with no counterweight is a slope rather than
    /// a loop. In RimWorld the counterweight to losing colonists is the stream of incidents that give you
    /// people; this is the only one of those this port ships.
    ///
    /// <para/><b>It joins through the machinery, not through a field.</b> <c>docs/design/player-first.md</c>'s
    /// rule cuts both ways — the world acting on the player has to reach its consequence through the
    /// simulation's own path too, or the arrival is a number written into a count. So the wanderer is
    /// generated by <see cref="PawnGenerator"/> from the same <see cref="PawnKindDefOf.Tribesperson"/> request
    /// shape <c>World.SettlementFounder</c> generates every founding citizen with, founds a household through
    /// <see cref="FamilyManager.FoundHousehold"/>, and is put on the roster with
    /// <see cref="Settlement.AddCitizen"/> — the exact three calls
    /// <see cref="MigrationManager.MigrationTick(Settlement, PawnKindDef)"/> already makes for an arriving
    /// migrant, which is the path a citizen who was not born here has always been supposed to take. Nothing
    /// new is invented and no count is incremented by hand: <see cref="Settlement.TotalPopulation"/>,
    /// <see cref="CivilizationTarget.PlayerPawnsForStoryteller"/> and the probe all move because a person is
    /// on the list they each derive from.
    ///
    /// <para/><b>Watched and unwatched need no branch here, and that is the point.</b>
    /// <see cref="Settlement.AddCitizen"/> is uniform — it enfactions the arrival and puts them on
    /// <see cref="Settlement.Citizens"/> whoever is looking — and the split lives one layer down in
    /// <see cref="Settlement.SyncCitizenSpawns"/>, which places a Full-tier citizen on the interior map when
    /// there is one and does nothing when there is not. A freshly generated <see cref="Pawn"/> starts at
    /// <see cref="PawnTier.Full"/>, so a wanderer joining a settlement the player has open stands up on its
    /// map immediately, and one joining a settlement nobody has entered is an ordinary Interval-tier citizen
    /// who falls to that tier on the next attention sweep — see
    /// <see cref="MigrationManager.ProcessArrivals"/>'s own doc, which settled this question for migrants and
    /// settles it here for the same reasons. Calling the sync rather than waiting for
    /// <see cref="Settlement.Tick"/>'s gated sweep mirrors <see cref="Settlement.EnterMap"/>'s own choice: the
    /// player is being handed a letter naming this person, and they should be there when it is read.
    ///
    /// <para/><b>What it does not do.</b> It does not stamp <see cref="Pawn.spawnedByIncident"/>. That field
    /// is read at the death funnel to credit a kill to its instigator's provenance
    /// (<see cref="StorytellerDeathEvents"/>), and a citizen is not an instigator — stamping it would mean a
    /// wanderer who later kills somebody in a mental break has their victim attributed to "the wanderer-join
    /// incident", which is a sentence no measurement wants to have to explain.
    ///
    /// <para/><b>Its dice are its own.</b> Every roll comes from <see cref="NamedRand"/>, and every roll is
    /// taken <i>before</i> the <see cref="Ablation"/> check so the ablated arm leaves the stream in exactly
    /// the position the live one does — see <see cref="NamedRand"/>'s "draw whether or not you act". The
    /// generator is called inside <see cref="Rand.PushState(int)"/> for the reason that doc gives and
    /// <see cref="IncidentWorker_ManhunterPack.Generate"/> learned the hard way: <see cref="PawnGenerator"/>
    /// draws ambiently and would otherwise shift every later roll in the game.
    /// </summary>
    public sealed class IncidentWorker_WandererJoin : IncidentWorker
    {
        /// <summary>The stream every roll in this incident comes from, qualified by the tick so two firings in
        /// one game differ while a replay of the same game does not — <see cref="IncidentWorker_ManhunterPack"/>'s
        /// own spelling, kept identical so the convention stays one convention.</summary>
        private const string StreamName = "WandererJoin";

        /// <summary>The wanderer the most recent successful firing produced, for a caller or test that wants to
        /// assert about them without re-deriving them. Mirrors <see cref="IncidentWorker_ManhunterPack.LastPack"/>
        /// and <see cref="IncidentWorker_TraderCaravanArrival.LastTrader"/>. Not saved: it is an inspection
        /// hook, and the citizen it names is owned by the settlement's own roster.</summary>
        public Pawn? LastWanderer { get; private set; }

        /// <summary>
        /// The settlement the most recent successful firing sent them to. Same rationale as
        /// <see cref="LastWanderer"/>.
        /// </summary>
        public Settlement? LastSettlement { get; private set; }

        protected override bool TryExecuteWorker(IncidentParms parms)
        {
            if (parms == null) throw new ArgumentNullException(nameof(parms));

            int now = Find.TickManager.TicksGame;
            RandomStream rand = NamedRand.For(
                StreamName + "|" + now.ToString(CultureInfo.InvariantCulture));

            // No civilization, or a civilization with nowhere to live, and the incident genuinely cannot
            // happen: a wanderer joins a settlement, and there is not one. Returning false is the whole point
            // of this rewrite — a worker that reports success having done nothing is the defect being fixed,
            // and reproducing it for the empty case would reintroduce it in a new place.
            //
            // Deliberately not also a CanFireNowSub override, unlike IncidentWorker_Disease's "is there anyone
            // to infect" and IncidentWorker_TraderCaravanArrival's "is there anyone to trade with". Those two
            // gate on states a shipped game can really be in (nobody healthy, no non-hostile trading faction).
            // A running game always has a settlement — Sim.Game attaches them every interval — so gating
            // CanFireNow on it would only ever be false for a target posed by hand in a test, and a gate that
            // cannot fire in play is a gate that costs a check on every comp evaluation to say nothing.
            if (!(parms.target is CivilizationTarget civilization)) return false;
            Settlement? settlement = civilization.ChooseTargetSettlement(rand);
            if (settlement == null) return false;

            // Every draw this incident will ever take, taken here, above the ablation gate. A defect that
            // advances its own stream differently when switched off is a defect that cannot be measured —
            // NamedRand's own doc, and the reason the two arms of a probe run stay comparable.
            //
            // For this worker in particular that ordering is discipline rather than something a test can
            // catch: the stream's name carries the tick, so every firing builds a fresh one from the world
            // seed and drops it, and where it was left is not readable from anywhere. The half that IS
            // observable — and is pinned, in both arms, by Firing_the_incident_does_not_disturb_the_ambient
            // _random_stream and Ablated_it_leaves_the_ambient_stream_exactly_where_the_live_one_does — is
            // Rand.Current's position. Keep the ordering anyway: the day somebody hoists this stream to
            // survive across firings, as NamedRand's doc describes a recurring caller doing, it starts
            // mattering silently.
            float age = rand.Range(MigrationTuning.MinMigrantAgeYears, MigrationTuning.MaxMigrantAgeYears);
            int generatorSeed = rand.Int;

            // Ablated: the storyteller picked this incident, the refire timer is spent, the stream has moved
            // exactly as far as it would have — and nobody arrives. Which is, exactly, the stub this file
            // replaces. See Ablation's own doc on why that coincidence is worth noticing rather than smiling at.
            if (Ablation.IsDisabled(def?.defName)) return true;

            Pawn wanderer = Arrive(settlement, age, generatorSeed, now);

            LastWanderer = wanderer;
            LastSettlement = settlement;

            // Named in the chronicle, not merely counted. Storyteller.TryFire already records that
            // "WandererJoin" fired; that entry cannot say who, and a civilization's history that knows a
            // wanderer arrived but not which one has lost the only part of it a player would retell. Same
            // "Prefix: sentence" shape MigrationManager's own arrival line uses, so MomentCurator's free-form
            // categoriser reads them as one kind of event rather than two.
            Find.Storyteller.RecordChronicle(
                "Wanderer: " + wanderer.Label + " joins " + PlaceLabel(settlement) + ".");

            SendLetter(settlement, wanderer);
            return true;
        }

        /// <summary>
        /// The whole arrival, generated the way a citizen is generated and attached the way a migrant is
        /// attached — under one <see cref="Rand.PushState(int)"/> scope.
        ///
        /// <para/><b>The scope covers all four calls, and it has to.</b> The obvious version wrapped only
        /// <see cref="PawnGenerator"/>, which is the one everybody knows draws ambiently, and it leaked: a
        /// test asserting the ambient stream is untouched across a firing came back one draw short, because
        /// <see cref="FamilyManager.FoundHousehold"/> asks
        /// <c>PawnBioAndNameGenerator.GenerateSurname</c> for the new household's name and that reads
        /// <see cref="Rand.Current"/>. This is exactly the leak <see cref="NamedRand"/>'s own doc describes —
        /// "a caller that holds a named stream and then invokes one of those has still moved the shared
        /// stream, and the leak is invisible: the caller's own rolls all look disciplined" — found the way
        /// that doc says it is found, by a test rather than by reading. Scoping the arrival rather than the
        /// generator means the next helper that quietly draws is covered before it is noticed.
        ///
        /// <para/><see cref="PawnKindDefOf.Tribesperson"/> because that is the kind
        /// <c>World.SettlementFounder</c> generates every founding citizen as — a wanderer becomes one of
        /// these people, so they are made of what these people are made of — and the settlement's own
        /// <c>faction</c> goes <i>into</i> the request rather than onto the pawn afterwards, which is
        /// load-bearing for the same reason it is load-bearing there:
        /// <c>PawnWeaponGenerator</c>/<c>PawnApparelGenerator</c> cap candidate gear at the faction's tech
        /// level, so a wanderer enfactioned after generation would arrive holding equipment the civilization
        /// they just joined cannot make. <see cref="Settlement.AddCitizen"/> would enfaction them anyway; this
        /// only makes sure it has nothing left to do.
        ///
        /// <para/>Age is drawn over <see cref="MigrationTuning"/>'s migrant band rather than the founder band:
        /// an arrival is old enough to found a household the moment they arrive and skews young, which is the
        /// judgement that constant already records for the one other way somebody walks into a settlement.
        ///
        /// <para/>The push/pop is not a flourish — see the class doc and <see cref="NamedRand"/>. A test pins
        /// that the ambient stream's position is unchanged across a firing.
        /// </summary>
        private static Pawn Arrive(Settlement settlement, float age, int generatorSeed, int now)
        {
            Rand.PushState(generatorSeed);
            try
            {
                Pawn wanderer = PawnGenerator.GeneratePawn(new PawnGenerationRequest(
                    PawnKindDefOf.Tribesperson, fixedBiologicalAge: age, faction: settlement.faction));

                Find.FamilyManager.FoundHousehold(wanderer, null, now);
                settlement.AddCitizen(wanderer);

                // Puts them on the interior map when the player has one open, and is a no-op when they do
                // not — see the class doc. Idempotent, and the same call EnterMap makes for the same reason.
                settlement.SyncCitizenSpawns();
                return wanderer;
            }
            finally
            {
                Rand.PopState();
            }
        }

        /// <summary>
        /// The player is told, by name. A person joining the settlement and the player never hearing about it
        /// is a non-event — worse here than for a threat, because this is the half of the loop that gives
        /// something back, and relief the player does not notice does not relieve anything.
        ///
        /// <para/>"Watched" is <c>God.AttentionManager.FocusedTile</c>, asked the same one-line way
        /// <see cref="IncidentWorker_ManhunterPack"/> and <c>IncidentWorker_RaidEnemy</c> ask it, so which
        /// settlement is being watched keeps having exactly one definition in this codebase. Not the
        /// arrival's own <see cref="PawnTier"/>, which <see cref="IncidentWorker_Disease"/> can use because
        /// its victim has been alive a while: a wanderer is Full-tier at this instant whoever is looking,
        /// because every freshly generated pawn is, so tier would answer "watched" every time.
        /// </summary>
        private static void SendLetter(Settlement settlement, Pawn wanderer)
        {
            string where = PlaceLabel(settlement);
            bool watched = Find.God.Attention.FocusedTile == settlement.tile;
            string text = watched
                ? $"{wanderer.Label} has wandered in and asks to stay. {where} has a new citizen."
                : $"Word reaches you late: {wanderer.Label} wandered into {where} and stayed, while your attention was elsewhere.";

            Find.LetterStack?.ReceiveLetter(
                "A wanderer joins: " + wanderer.Label,
                text,
                LetterDefOf.PositiveEvent,
                new List<string> { wanderer.GetUniqueLoadID() });
        }

        private static string PlaceLabel(Settlement settlement) =>
            string.IsNullOrEmpty(settlement.name) ? "the settlement" : settlement.name;
    }
}
