using SimWorld.Noise;
using SimWorld.Sim;

namespace SimWorld.MapGen
{
    /// <summary>
    /// Builds the two per-cell noise grids every later step reads: a 0..1 elevation field (which cell of the
    /// tile reads as higher, rocky ground) and a 0..1 fertility field (which cell reads as richer soil). Both
    /// are local-only texture — the tile's own elevation/rainfall/hilliness (already generated by world gen)
    /// decide the map's overall character; this step only decides which cell within it gets which texture.
    /// </summary>
    public class GenStep_ElevationFertility : GenStep
    {
        public override void Generate(MapGenContext ctx)
        {
            RandomStream rand = SeededStream(ctx);
            Map.Map map = ctx.map;
            int sizeX = map.Size.x, sizeZ = map.Size.z;
            int n = map.cellIndices.NumGridCells;
            int baseSeed = rand.Int;

            var elevationNoise = new Perlin(frequency: MapGenTuning.NoiseFrequency, lacunarity: 2.0, persistence: 0.5, octaveCount: 5, seed: baseSeed, quality: NoiseQuality.Standard);
            var fertilityNoise = new Perlin(frequency: MapGenTuning.NoiseFrequency * 0.75, lacunarity: 2.0, persistence: 0.5, octaveCount: 4, seed: baseSeed + 1000, quality: NoiseQuality.Standard);

            var elevation = new float[n];
            var fertility = new float[n];
            double invSizeX = 1.0 / sizeX;
            double invSizeZ = 1.0 / sizeZ;

            for (int z = 0; z < sizeZ; z++)
            {
                double nz = z * invSizeZ;
                for (int x = 0; x < sizeX; x++)
                {
                    int i = map.cellIndices.CellToIndex(x, z);
                    double nx = x * invSizeX;
                    elevation[i] = GenMath.Clamp01((float)elevationNoise.GetValue(nx, 0.0, nz) * 0.5f + 0.5f);
                    fertility[i] = GenMath.Clamp01((float)fertilityNoise.GetValue(nx, 0.0, nz) * 0.5f + 0.5f);
                }
            }

            ctx.elevationGrid = elevation;
            ctx.fertilityGrid = fertility;
        }
    }
}
